# -*- coding: utf-8 -*-
"""HospitalDatas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Wemv8--gC7upuwcId81fMbBSTx6tF_3p
"""
from urllib.parse import urlencode, unquote, quote_plus
import requests
from bs4 import BeautifulSoup as bs
from .datas import datas, subs

class Api:
    #input: ['0페이지번호', '1한 페이지 결과수', '2시도코드', '3시군구코드', '4읍면동명',
    # '5병원명', '6분류코드', '7종별코드', '8진료과목코드', '9x좌표', '10y좌표', '11반경']
    #datas: [0index, 1병원명, 2로마자병원명, 3병원명, 4주소, 5병원분류, 6시도, 7시군구,
    # 8읍면동, 9우편번호, 10전화번호, 11홈페이지, 12설립년도, 13총의사수, 14x좌표, 15y좌표]
    def __init__(self, arr):
        self.arr = arr
        self.value = []
        self.dataset = []
        self.pageNow = 0
        self.pageTotal = 0

    def target(self, target):  # 입력 변수 arr, 읽으려는 값 target
        self.value = []
        self.dataset = []
        i = 0
        if target == 'yadmnm': i = 1
        elif target == 'addr': i = 4
        elif target == 'telno': i = 10
        elif target == 'hospurl': i = 11
        if self.arr[5] == '':
            if self.arr[8] != '':
                n = int(self.arr[8])
                if n in range(27): pass
                elif n in range(50, 60) : n = n - 23
                elif n == 61: n = 37
                else: n = n - 42
                self.dataset = subs[n][2:]
                for x in self.dataset[(int(self.arr[0]) - 1) * int(self.arr[1]) : int(self.arr[0]) * int(self.arr[1])]:
                    self.value.append(x)
            else:
                self.dataset = datas
                for x in self.dataset[(int(self.arr[0]) - 1) * int(self.arr[1]) : int(self.arr[0]) * int(self.arr[1])]:
                    if x[i] != -1: self.value.append(x[i])
        else:
            self.dataset = [x for x in datas if x[1] == self.arr[5]][0]
            if self.dataset[i] != -1: self.value.append(self.dataset[i])

    def page(self):
        self.pageNow = self.arr[0]
        l = len(self.dataset)
        self.pageTotal = (l + int(self.arr[1]) - 1) // int(self.arr[1])

class Hospital:
    def __init__(self, name, romanname, addr, romanaddr, telno, url, xpos, ypos, pageNow, pageTotal):
        self.name=name
        self.romanname=romanname
        self.addr=addr
        self.romanaddr=romanaddr
        self.telno=telno
        self.url=url
        self.xpos=xpos
        self.ypos=ypos
        self.pageNow=pageNow
        self.pageTotal=pageTotal

class Pos:
    def __init__(self, name, romanname, xpos, ypos):
        self.name = name
        self.romanname = romanname
        self.xpos=xpos
        self.ypos=ypos

